### ISSUE TITLE
Formatting des données

### ISSUE THREAD

**Issue by thomasp05** [thomasp05/GIF-7005-Projet#2]
Loader les données en qui sont en format dcm et les convertir en format pytorch

**Comment by igorpontes** [comment]
je crois que cet issue est déjà fait, n'est-ce pas @ludovicgirard ?

**Comment by ludovicgirard** [comment]
J'ai une idée de truc à ajouter qui est un peu en lien, je vais ouvrir un nouvel issue pour ça.
