### ISSUE TITLE
Tester le model U-net

### ISSUE THREAD

**Issue by thomasp05** [thomasp05/GIF-7005-Projet#4]

**Comment by ludovicgirard** [comment]
L'implémentation de U-Net dans models.py (main branch) ne semble pas fonctionner. Celle dans train.ipynb (test-unet branch) semble correcte. On déplace donc l'implémentation de train.ipynb vers models.py? @igorpontes

**Comment by igorpontes** [comment]
c'est déplacé @ludovicgirard. Tout est dans la PR #15
