### ISSUE TITLE
Méthode de segmentation pour détection de zone 

### ISSUE THREAD

**Issue by thomasp05** [thomasp05/GIF-7005-Projet#7]

**Comment by igorpontes** [comment]
quels sont les méthodes? U-Net, quels sont les autres?

**Comment by ludovicgirard** [comment]
Est-ce que seulement U-Net est suffisant? Si on veut en comparer plusieurs, je propose d'implémenter un FCN tiré de cet article: 
https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Long_Fully_Convolutional_Networks_2015_CVPR_paper.pdf
